### ISSUE TITLE
Infografia_IrvingFernando

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-IrvingFernand0#2]
[Infografia_IrvingFernandoReyesPacheco.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-IrvingFernand0/files/12457868/Infografia_IrvingFernandoReyesPacheco.pdf)

**Comment by abicoronel** [comment]
calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
